### ISSUE TITLE
Doesn't work with MSAA

### ISSUE THREAD

**Issue by neon-age** [CMDRSpirit/URPTemporalAA#2]
Missing shader. PostProcessPass render pass will not execute. Check for missing reference in the renderer resources.

![image](https://user-images.githubusercontent.com/29812914/164872938-40d5de9b-21b4-4923-b0b7-3f7205ca43e2.png)

**Comment by CMDRSpirit** [comment]
I haven't looked at MSAA framebuffers yet, but TAA is a replacement for MSAA (correct me if I'm wrong), so that shouldn't be a problem if it is unsupported in general.

**Comment by neon-age** [comment]
> TAA is a replacement for MSAA (correct me if I'm wrong)

PPV2 supported TAA + MSAA and yielded better detailed results with this extra information, and it becomes way less jittery, which is very noticeable on detailed surfaces/edges, like weapons or thin edges in far away

https://user-images.githubusercontent.com/29812914/214443603-030dacb3-ecb2-4929-ae47-54929ab5e9fa.mp4

**Comment by CMDRSpirit** [comment]
Yes quality wise, but only when you look at geometry edges. Alpha tested textures and lighting edges, like shadows, specular highlights, ... are unaffected by MSAA by definition of how the method works. You will also get a performance penalty as you need to calculate lighting multiple times per pixel (For every subpixel sample of MSAA). Additionally, deferred rendering will be inefficient if it is supported at all (don't know at the moment what URP does), because you can't interpolate geometry data, like normals, depth, ...

That is basically why I think it is not worth the time to implement a compatibility with a technique that is basically dead when it comes to supporting more recent graphics featured.
You can read more on the HDRP doc about their problems with MSAA:
https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@15.0/manual/Anti-Aliasing.html#MSAA)
